### ISSUE TITLE
While donwloading if I press the check buton everything become mess

### ISSUE THREAD

**Issue by punsith** [HaikuArchives/BePodder#6] opened 2016-12-21 22:12 UTC
The downloading is like "14%" then it gose to "1%" then again "3%" just like random numbers  video is on this link :: 
https://drive.google.com/open?id=0B7xGWjXyxh6HVUhIcEhRd28tYzQ

**Comment by janus2** [comment] 2017-12-11 15:45
I can't reproduce the problem. Can you post the link of the feed that gives you problem? From the video looks like you are trying to download a video instead of a feed. Am I wrong?
The application should reply invalid format.

**Comment by janus2** [comment] 2018-03-17 07:39
I close this for now. If happen again please reopen.

**Closed** 2018-03-17 07:42 UTC
